---
name: Docker Image CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    paths:
      - '**/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: slavik0/debian-10-systemd
            dockerfile: debian-11-systemd/Dockerfile
          - image: slavik0/debian-11-systemd
            dockerfile: debian-11-systemd/Dockerfile
          - image: slavik0/debian-12-systemd
            dockerfile: debian-12-systemd/Dockerfile
          - image: slavik0/debian-13-systemd
            dockerfile: debian-13-systemd/Dockerfile
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # platforms: "linux/amd64,linux/arm64,linux/arm/v7"
          platforms: "linux/amd64"
